### ISSUE TITLE
Photo's orientation

### ISSUE THREAD

**Issue by JasminLink** [dime-project/meta#1]
When uploading a photo from a smartphone, the image changed its orientation and is now shonw upside down. I'm lefthanded, so I'll stumble upon things like that more likely than people who turn their phone the "right" way... 

It was this one: 
![img_0112](https://f.cloud.github.com/assets/5270356/993784/24b810d8-09a1-11e3-8712-ce96853d6c8d.JPG)

**Comment by thielsn** [comment]
Thanks for the feedback!

Will add it to the list of requested features :-)
