### ISSUE TITLE
My data editing issues

### ISSUE THREAD

**Issue by andrewbuttigieg** [dime-project/meta#16]
Some issues detected whilst using Safari on iPad 4:

1) updating a data name does not update the text in the "all documents" area. You need to refresh the page to fix it.

2) pages are much longer than they should be (you can scroll well after the page is "finished").

3) when you search for data and find nothing, you cannot get back to the state whee you have just "your" data without refreshing the page.

4) search does not right trim white spaces.

**Comment by thielsn** [comment]
Thanks for the issue documentation:
1) the updating issue is unfortunately a known issue, with the server (system notifications are missing on updating a resource)
2) a problem with the floating meta-bar - might be fixed later
3) its possible to click on MyData in Navigation - however this might not be intuitive enough
4) this has been fixed now :-)
