### ISSUE TITLE
defProfile for merged persons is an array instead of a single value

### ISSUE THREAD

**Issue by thielsn** [dime-project/meta#17]
defProfile for merged persons is an array instead of a single value - see json below:

see also https://github.com/dime-project/meta/issues/18

{
"response":{
"meta":{
"status":"OK",
"code":200,
"timeRef":1382429844872,
"v":"0.9",
"msg":""
},
"data":{
"startIndex":0,
"itemsPerPage":1,
"totalResults":1,
"entry":[
{
"guid":"urn:uuid:78d1dc25-59b1-4c33-a448-d57dbb8edd9c",
"type":"person",
"pimo:occurrence":[
"urn:uuid:d311c014-05df-4bc5-922e-1ab15a325ede",
"urn:uuid:4b12aa73-3499-40d5-9e08-a3753337d8d9"
],
"name":"Rafa Giménez",
"defProfile":[
"p_urn:uuid:d311c014-05df-4bc5-922e-1ab15a325ede",
"p_urn:uuid:4b12aa73-3499-40d5-9e08-a3753337d8d9"
],
"nao:hasDataGraph":"user:dummy7002:PIM",
"created":1382424944182,
"nao:modified":1381840964903,
"nao:trustLevel":0.5,
"lastModified":1382424944185,
"pimo:memberOf":[
"urn:uuid:a6d63d01-abfc-42c7-ba74-7f32a43010fa",
"urn:uuid:de913e10-b6aa-418a-af1f-d8893811c722"
],
"userId":"@me",
"imageUrl":"",
"items":[
]
}
]
}
}
}

**Comment by ismriv** [comment]
Fixed on commit https://github.com/dime-project/dime-server/commit/a883266638f538c5af85ef0e331fa9acfb12bef4
