### ISSUE TITLE
Mobile Client shows (wrong) IP address as default server

### ISSUE THREAD

**Issue by thielsn** [dime-project/meta#19]
When starting the mobile client in "server" a confusing IP is automatically filled in. 

Workaround:
To get the full list of servers available, the entry has to be deleted first by the user. 

Fix:
the field server should be empty when not set.

**Comment by christian-knecht** [comment]
Issue is fixed now:
- the DEFAULT_HOSTNAME is changed to "dime.hci.iao.fraunhofer.de"
- server selection in login dialog is improved
- adding and removing of own servers implemented
