### ISSUE TITLE
Duplicated information when setting up a location

### ISSUE THREAD

**Issue by danielalcazar** [dime-project/meta#2]
The first time I entered in the Location option (upper right menu) and I enter a search string, the recommended steps to follow (add the YellowMapPlace service) are shown one after another after clicking the search button (or enter).
![screen shot 2013-08-24 at 10 42 44 am](https://f.cloud.github.com/assets/5300175/1020396/546d2cdc-0c99-11e3-9389-ebb5dff48312.png)

**Comment by danielalcazar** [comment]
The text is copied every time enter (or search button) is clicked.
Once the subscription to YellowMapPlace service is done, the text doesn´t appear anymore, so the bug is not relevant in that case.

**Comment by patricksvgr** [comment]
It should be fixed now. Thanks!
