### ISSUE TITLE
MalformedQueryException for GET resource @me/@all call

### ISSUE THREAD

**Issue by christian-knecht** [dime-project/meta#20]
After editing the privacy value of a resource all GET resource @me/@all calls are failing with following error message:

02-03 20:05:17.324: E/RestApiAccess(575): Error:
02-03 20:05:17.324: E/RestApiAccess(575): call:/dime-communications/api/dime/rest/dummy2002/resource/@me/@all
02-03 20:05:17.324: E/RestApiAccess(575): payload:
02-03 20:05:17.324: E/RestApiAccess(575): code:200
02-03 20:05:17.324: E/RestApiAccess(575): message:
02-03 20:05:17.324: E/RestApiAccess(575): OK
02-03 20:05:17.324: E/RestApiAccess(575): reply:
02-03 20:05:17.324: E/RestApiAccess(575): {"response":{"meta":{"status":"ERROR","code":500,"timeRef":1383903440092,"v":"0.9","msg":"org.openrdf.query.MalformedQueryException: Not a valid (absolute) URI: /dime-communications/api/dime/rest/dummy2002/resource/filemanager/urn%3Auuid%3A7a18a581-be3d-443b-b4bd-b31aad6691b1"}}}
02-03 20:05:17.324: E/RestApiAccess(575): Entry:
02-03 20:05:17.324: E/RestApiAccess(575): {
02-03 20:05:17.324: E/RestApiAccess(575):   "response":{
02-03 20:05:17.324: E/RestApiAccess(575):       "meta":{
02-03 20:05:17.324: E/RestApiAccess(575):           "status":"ERROR",
02-03 20:05:17.324: E/RestApiAccess(575):            "code":500,
02-03 20:05:17.324: E/RestApiAccess(575):            "timeRef":1383903440092,
02-03 20:05:17.324: E/RestApiAccess(575):            "v":"0.9",
02-03 20:05:17.324: E/RestApiAccess(575):            "msg":"org.openrdf.query.MalformedQueryException: Not a valid (absolute) URI: /dime-communications/api/dime/rest/dummy2002/resource/filemanager/urn%3Auuid%3A7a18a581-be3d-443b-b4bd-b31aad6691b1"}}}

**Comment by bgorriz** [comment]
There was a bug now fixed on resource controller
