### ISSUE TITLE
problem with merge suggestion

### ISSUE THREAD

**Issue by christian-knecht** [dime-project/meta#21]
After accepting the merge suggestion to merge own profile (!) with some other persons profile I get following error message for all REST calls:
{"response":{"meta":{"status":"ERROR","code":400,"timeRef":1384360606383,"v":"0.9","msg":"cannot find current user/PIM owner: eu.dime.ps.semantic.exception.NotFoundException: Resource user:dummy2008:me does not exist."}}}
The whole model seems to be broken.

**Comment by ismriv** [comment]
Fixed: commit ff512fb13992ab3d4f692861653a9057cfe1e9f9

Now, the user owner of the PIM or data store cannot be merged with other persons.
