### ISSUE TITLE
Test fail: eu.dime.ps.communications.requestbroker.controllers.infosphere.PSPersonControllerTestIt

### ISSUE THREAD

**Issue by thielsn** [dime-project/meta#24]
## Test set: eu.dime.ps.communications.requestbroker.controllers.infosphere.PSPersonControllerTestIt

Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.145 sec <<< FAILURE!
testDefProfileDimeAccount(eu.dime.ps.communications.requestbroker.controllers.infosphere.PSPersonControllerTestIt)  Time elapsed: 0.118 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<25>
        at eu.dime.ps.communications.requestbroker.controllers.infosphere.PSPersonControllerTestIt.testDefProfileDimeAccount(PSPersonControllerTestIt.java:98)

**Comment by bgorriz** [comment]
fixed
