### ISSUE TITLE
multipart upload from mobile client not working

### ISSUE THREAD

**Issue by christian-knecht** [dime-project/meta#25]
Uploading Files from mobile is not working:
- resource is added to list
- thumbnail was created properly
- all meta files seem to be ok (file size etc.)
  but error opening file (Error 400). Is the URL correct:
  dime-communications/api/dime/rest/dummyreviewprepXX/resource/filemanager/file%3A%2Fstorage%2Femulated%2F0%2FDCIM%2FCamera%2FIMG_20131125_160415.jpg?

**Comment by thielsn** [comment]
was closed by accident ;-)

However, the problem seems to be with the controller handling the file upload for multipart. Potentially something was broken, when fixing the thumbnail for the other upload endpoint used by the web-UI...
