### ISSUE TITLE
postal code not stored for profile attribute

### ISSUE THREAD

**Issue by christian-knecht** [dime-project/meta#26]
{
    "type": "profileattribute",
    "guid": "<someGUID>",
    "category": "PostalAddress",
    "userId": "@me",
    "name": "My Address",
    "value": {
        "streetAddress": "XXX",
        "region": "XXX",
        "extendedAddress": "00",
        "addressLocation": "XXX",
        "pobox": "",
        "locality": "",
        "country": "Germany"
    },
    "predicate": "nco:hasPostalAddress"
}

-> postal code missing -> https://github.com/dime-project/meta/wiki/Profile-attribute

![postaladress-items](https://f.cloud.github.com/assets/4630065/1615659/8bcf3a6e-55fd-11e3-91be-2f64866d804a.png)

**Comment by bgorriz** [comment]
fixed
