### ISSUE TITLE
POST Situation is not coming back

### ISSUE THREAD

**Issue by thielsn** [dime-project/meta#31]
When click on "Activate" for a second Situation, the POST is not coming back (pending) for ever...

Last Method in the log:
2013-11-28 08:00:34 PSSituationController [INFO] called API method: POST /dime/rest/dummy5500/situation/@me/update/urn:uuid:b32ad946-a3a3-475d-a5ce-d5391b7b1dce

Payload

{"request":{"meta":{"v":"0.9","status":"OK","code":200,"timeRef":1385622034587},"data":{"startIndex":0,"itemsPerPage":1,"totalResults":1,"entry":[{"guid":"urn:uuid:b32ad946-a3a3-475d-a5ce-d5391b7b1dce","type":"situation","name":"Travelling","nao:creator":"user:dummy5500:me","dc:creator":"user:dummy5500:me","dcon:hasContextAspect":["urn:uuid:7e6ccba6-8331-4ca8-ab9c-6ad21261e22b","urn:uuid:6bb7ed7d-f707-4af5-aee1-bbf4310582bf"],"nao:score":0.49,"created":1385621794803,"nao:modified":1385621794804,"lastModified":1385621794804,"nao:isDataGraphFor":"urn:uuid:b32ad946-a3a3-475d-a5ce-d5391b7b1dce","nao:hasDataGraph":"urn:uuid:b32ad946-a3a3-475d-a5ce-d5391b7b1dce","userId":"@me","imageUrl":"https://127.0.0.1:8443/dime-communications/static/ui/dime/icons/situation_general.png","items":[],"active":true,"contextElements":[{"guid":"user:dummy5500:LateEvening","dcon:isRequired":false,"dcon:weight":0.6,"imageUrl":null,"name":"Late Evening","dcon:isExcluder":false,"type":"dcon:currentTime"},{"guid":"user:dummy5500:EarlyAfternoon","dcon:isRequired":false,"dcon:weight":0.6,"imageUrl":null,"name":"Early Afternoon","dcon:isExcluder":false,"type":"dcon:currentTime"},{"guid":"user:dummy5500:EarlyNight","dcon:isRequired":false,"dcon:weight":0.3,"imageUrl":null,"name":"Early Night","dcon:isExcluder":false,"type":"dcon:currentTime"},{"guid":"user:dummy5500:LateMorning","dcon:isRequired":false,"dcon:weight":0.4,"imageUrl":null,"name":"Late Morning","dcon:isExcluder":false,"type":"dcon:currentTime"},{"guid":"user:dummy5500:Station","dcon:isRequired":false,"dcon:weight":0.9,"imageUrl":null,"name":"Station","dcon:isExcluder":false,"type":"dcon:currentPlace"},{"guid":"user:dummy5500:LateNight","dcon:isRequired":false,"dcon:weight":0.2,"imageUrl":null,"name":"Late Night","dcon:isExcluder":false,"type":"dcon:currentTime"},{"guid":"user:dummy5500:EarlyEvening","dcon:isRequired":false,"dcon:weight":0.2,"imageUrl":null,"name":"Early Evening","dcon:isExcluder":false,"type":"dcon:currentTime"},{"guid":"user:dummy5500:EarlyMorning","dcon:isRequired":false,"dcon:weight":0.7,"imageUrl":null,"name":"Early Morning","dcon:isExcluder":false,"type":"dcon:currentTime"},{"guid":"user:dummy5500:Airport","dcon:isRequired":false,"dcon:weight":0.8,"imageUrl":null,"name":"Airport","dcon:isExcluder":false,"type":"dcon:currentPlace"},{"guid":"user:dummy5500:LateAfternoon","dcon:isRequired":false,"dcon:weight":0.3,"imageUrl":null,"name":"Late Afternoon","dcon:isExcluder":false,"type":"dcon:currentTime"},{"guid":"user:dummy5500:Driving","dcon:isRequired":false,"dcon:weight":0.5,"imageUrl":null,"name":"Driving","dcon:isExcluder":false,"type":"dcon:currentActivity"},{"guid":"user:dummy5500:Travelling","dcon:isRequired":false,"dcon:weight":1,"imageUrl":null,"name":"Travelling","dcon:isExcluder":false,"type":"dcon:currentActivity"}]}]}}}

Tested with

https://github.com/dime-project/dime-server/commit/88036eba8f917dc1a63ec0de831d701ccd5d67aa

**Comment by ismriv** [comment]
Fixed.
