### ISSUE TITLE
Forgotten username

### ISSUE THREAD

**Issue by JasminLink** [dime-project/meta#6]
Although I appreciate the unintrusive approach of di.me I#m kind of lost because I don't know the username I  picked for the new account anymore... And unlike any other system di-me didn't send me any "Welcome <username>, Thanks for registering..."-mail and I can't see any way how to get to my username... I remeber my password, and I remeber the e-mail address, but that seems to be of no help. 
As a feature for the forgetful folks some it would be nice to be able to login with the e-mail adress or rerieve pw/username somehow. ;-)

**Comment by thielsn** [comment]
True. 

The current solution is to ask your friendly administrator to send an email :-)

For the Fraunhofer server this is me (simon.thiel@iao.fraunhofer.de).

**Comment by thielsn** [comment]
Was added to the feature request list.
