### ISSUE TITLE
high CPU load after update; and log is spammed with "Similarity score" messages

### ISSUE THREAD

**Issue by thielsn** [dime-project/meta#7]
Okt 03, 2013 12:05:42 AM ie.deri.smile.context.semmf.SemMFContextMatcher match
INFO: Similarity score for candidate urn:uuid:8405cf95-574b-48c5-9ce5-e52e882b5998 is NaN
based on lc
...

about one entry per 10 seconds ...

Please check, whether this is a bug, or handle it silently.

**Comment by thielsn** [comment]
There is also a problem with CPU usage! - top reports more than 100% continuously and jconsole: 
![increasedcpuloadafterredeploy_](https://f.cloud.github.com/assets/4115477/1257993/bf7c1d52-2bb2-11e3-86ba-30484125f017.png)

**Comment by thielsn** [comment]
There is also a memory issue with this - the garbage collector is really busy... - has never been the case before.

![increasedcpuloadafterredeploy2](https://f.cloud.github.com/assets/4115477/1267861/ea91c6dc-2cce-11e3-8dc9-2126be0f6d74.png)

**Comment by ismriv** [comment]
Change frequency of situation detection, and modified log4j properties to only log warnings and errors. This has been moved to a branch: https://github.com/dime-project/dime-server/tree/semmf-context-matching

**Comment by thielsn** [comment]
Closed since branch will be tested separately. (Before merging to master again...)
